In [ ]:
# This notebook demonstrates the one-loop bubble RL environment without training

In [1]:
from pyfeyngym import IBPEnv, visualize_board
import gymnasium as gym
import numpy as np

Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython


In [2]:
# Create an environment with a randomly selected target integral
env = IBPEnv(random_target = True)

In [3]:
# Equivalently, you could write
env = gym.make("pyfeyngym-v0", random_target = True)
env = env.unwrapped # Access the raw environment which has more methods than the standard gymnasium interface

In [4]:
# Set tk backend for matplotlib if possible
from IPython import get_ipython
ip = get_ipython()
try:
    ip.run_line_magic("matplotlib", "tk")
except Exception:
    ip.run_line_magic("matplotlib", "inline")

In [5]:
# Currently, visualizing the environemnt shows just an empty board with the target integral marked as a red square
fig, ax, anim = env.visualize()

In [6]:
# This is the list of all possible actions, as (x coordinate, y coordinate, action type).
# x and y coordinates are the powers of the two propagators of the bubble Feynman diagram
# action type 1 and 2 are the two types of IBP equations, and action type 0 corresponds to
# eliminating the integral in Gaussian elmination
[np.array(a) for a in env.all_actions_2d] # np.array converts Julia arrays to numpy arrays for display here

[array([-1, -1,  0]),
 array([-1,  0,  0]),
 array([-1,  1,  0]),
 array([-1,  2,  0]),
 array([-1,  3,  0]),
 array([-1,  4,  0]),
 array([-1,  5,  0]),
 array([-1,  6,  0]),
 array([-1,  7,  0]),
 array([ 0, -1,  0]),
 array([0, 0, 0]),
 array([0, 1, 0]),
 array([0, 2, 0]),
 array([0, 3, 0]),
 array([0, 4, 0]),
 array([0, 5, 0]),
 array([0, 6, 0]),
 array([0, 7, 0]),
 array([ 1, -1,  0]),
 array([1, 0, 0]),
 array([1, 1, 0]),
 array([1, 2, 0]),
 array([1, 3, 0]),
 array([1, 4, 0]),
 array([1, 5, 0]),
 array([1, 6, 0]),
 array([1, 7, 0]),
 array([ 2, -1,  0]),
 array([2, 0, 0]),
 array([2, 1, 0]),
 array([2, 2, 0]),
 array([2, 3, 0]),
 array([2, 4, 0]),
 array([2, 5, 0]),
 array([2, 6, 0]),
 array([2, 7, 0]),
 array([ 3, -1,  0]),
 array([3, 0, 0]),
 array([3, 1, 0]),
 array([3, 2, 0]),
 array([3, 3, 0]),
 array([3, 4, 0]),
 array([3, 5, 0]),
 array([3, 6, 0]),
 array([3, 7, 0]),
 array([ 4, -1,  0]),
 array([4, 0, 0]),
 array([4, 1, 0]),
 array([4, 2, 0]),
 array([4, 3, 0]),
 array([

In [7]:
# let's look at the valid actions at this step, given as numerical indices with respect to the above list
env.define_valid_actions()

array([ 92,  93,  94,  95,  96,  97, 100, 101, 102, 103, 104, 105, 106,
       109, 110, 111, 112, 113, 114, 115, 118, 119, 120, 121, 122, 123,
       124, 127, 128, 129, 130, 131, 132, 133, 136, 137, 138, 139, 140,
       141, 142, 145, 146, 147, 148, 149, 150, 151, 173, 174, 175, 176,
       177, 178, 181, 182, 183, 184, 185, 186, 187, 190, 191, 192, 193,
       194, 195, 196, 199, 200, 201, 202, 203, 204, 205, 208, 209, 210,
       211, 212, 213, 214, 217, 218, 219, 220, 221, 222, 223, 226, 227,
       228, 229, 230, 231, 232])

In [8]:
# Take an arbitrary action, e.g. 92
observation, reward, terminated, truncated, info = env.step(92)

In [9]:
# observation is a 2D image with resolution 9*9 with 4 channels. The first three channels simply
# indicate whether the three types of actions have been taken for the particular cell, and the 4th
# channel is 0 for most cells and 1 for the cell of the target integral.
observation

array([[[ 0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]],

      

In [10]:
# info contains the action mask, a boolean array indicating which ones in the list of all actions are valid
info

{'action_mask': array([False, False, False,  True, False, False, False, False, False,
        False, False, False,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False

In [11]:
# visualizing the environment now shows one seed integral / IBP operator used
fig, ax, anim = env.visualize()

In [12]:
# Let take an action, again the first one in the list of valid actions
observation, reward, terminated, truncated, info = env.step(env.define_valid_actions()[0])

In [13]:
env.action_log()

array([[ 0,  1,  1],
       [-1,  2,  0]])